### ISSUE TITLE
preview of a coming great project

### ISSUE THREAD

**Issue by Heartbreaker16** [cjLiu666/cJSON#1]
does the project aim to provide a json parser which is faster than other well-known open-source projects with the power of C ?

**Comment by cjLiu666** [comment]
No, Just for study and the implement is the same as [cJSON.](https://github.com/DaveGamble/cJSON). cJSON is a fantastic project, including its data struct, generic programming and DFA. Its code style also deserves to be learned by us.

**Comment by cjLiu666** [comment]
cJSON has a lot of places to be optimized. Such as memory manage and smart points.
